### ISSUE TITLE
Authentication with username/password possible?

### ISSUE THREAD

**Issue by bluepuma77** [omarryhan/pyfy#12]
I would like to use `pyfy` on a headless Raspberry Pi Zero, which makes the current authentication mechanisms rather complicated.

Therefore I would like to know if it's possible to authenticate with username/password - even though it's probably not the preferred solution from a security perspective.

**Comment by omarryhan** [comment]
Unfortunately, it isn't possible. Is it for personal use, or will the raspberry pi serve multiple people?

If it's for personal use,  you can get an access and refresh tokens using your pc and then hard code them into the code that will be executed on your Raspberry Pi. The creds will last you forever.

If it's going to serve multiple people, then I imagine running a web server on your pi would be your best bet. I have an example of an authentication backend in the examples folder. You'll only need to add code that stores the access and refresh token somewhere on your pi. Then, you'll implement some access control logic. On the bright side, you won't need to write much html for authentication.

**Comment by omarryhan** [comment]
Feel free to reopen this issue if you have further questions.
