### ISSUE TITLE
TypeError � is not JSON serializable

### ISSUE THREAD

**Issue by ykelle** [omarryhan/pyfy#14]
When using the example "save_user_creds.py" often the error "TypeError � is not JSON serializable" is thrown.

> Traceback (most recent call last):
>   File "/Users/.../Documents/PycharmProjects/spotipy-control/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
>     response = await response
>   File "/Users/.../Documents/PycharmProjects/spotipy-control/tests/spotifyWebApiTest.py", line 60, in spotify_callback
>     user_creds.save_as_json(path='/Users/.../Documents/PycharmProjects/spotipy-control/tests', name='spotify_cred.json')
>   File "/Users/.../Documents/PycharmProjects/spotipy-control/venv/lib/python3.7/site-packages/pyfy/creds.py", line 109, in save_as_json
>     json.dump(self.__dict__, outfile)
> TypeError: � is not JSON serializable

Sometimes when running the example there is no error and the credentials are saved.
Maybe using` __dict__` to save object as JSON will not work in all cases?

Best regards

**Comment by omarryhan** [comment]
Refer to #13
