### ISSUE TITLE
KeyError: 'collaborative' when using .create_playlist

### ISSUE THREAD

**Issue by footykid3** [omarryhan/pyfy#7]
I am not able to create a playlist 

spt = Spotify('my_code')

spt.create_playlist("Test name")

line 85, in <module> spt.create_playlist("test name")
line 133, in sync_wrapper request = request_factory(*args_with_injections, **kwargs_with_injections)

line 522, in _prep_create_playlist data['collaborative']
KeyError: 'collaborative'

**Comment by omarryhan** [comment]
Thank you for reporting this issue. Just released a fix.
